# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7e26650d9265c68517d3fd0867e5b2123f6d34c93da87d4942e876334ed26856f16e62a244e5e2e7c05f9937a3190590bbaf56d263bd488742be271f3384951

test:
  secret_key_base: 883e24da87334a8af52d683a5e6a14532cb42b7e4bdb78039fb57a63fcfeac10f2032b99e11c607c68b7574d95ab3a310189b6efc35fca26ed4797b5d3ab34f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
